### PR TITLE
Build a (minified) version for CDN delivery

### LINKED ISSUE #31: Build a (minified) version for CDN delivery
Currently the user has to install the library with a package manager. I think it would be a good idea to build a (minified) version of the lib each time the `main` branch gets updated. This way the user can just include a script tag with a CDN's url (e.g. https://unpkg.com/@turingpointde/cvss.js@1.2.0/production.min.js) and use the library.

I do not really know if GitHub Actions can modify commits or add this to a merge commit. But what we would need ideally is:

1. A config/tool to build a (minified) version of the library
2. A Github action that builds the library automatically and updates the repo if changes are merged into main

### PR DESCRIPTION
**Pull request by mrewers**
# Description

This addresses issue #31 by adding a build script to compile and minify the code using Webpack. The bundle is written to the `dist` directory and compiled under the library name CVSS. I also changed the main field in the `package.json` so users installing via NPM will continue to have the same experience. The build can be initiated by running `yarn build`.

I don't believe that you can add a GitHub action to build and commit those changes. As such, I used [husky](https://www.npmjs.com/package/husky) to add a pre-commit hook that will run the compilation on every commit. This is almost certainly overkill and will probably get annoying. I initially tried add the build step as a pre-push hook, but this would fail when trying to push changes that did not alter the production bundle. Typically, I would do this upon versioning package as a post-version hook. It seems like you are using versioning, but I only saw the one git tag (v1.3.0) so I wasn't certain. Let me know if you want me to make that change.

Fixes #31 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Fubinator** [comment]
Yeah, I plan to create tags for each release. I also do not think we should use the pre-commit hook. I would have thought that maybe we could build and commit with an auto-commit action on every release. 

Here is an action for auto commiting: https://github.com/stefanzweifel/git-auto-commit-action

Since I don't know that much about Github Actions myself, I'm open for completely different solutions to the problem. I could of course build manually while raising the version, but that could lead to errors (e.g. forgetting to build).

Should we maybe just merge the build part here and discuss automatic building in a new issue?

**Comment by mrewers** [comment]
Sounds good @Fubinator. I removed the pre-commit hook and rebased my branch off of `main` so that this PR just adds the build step.

A cursory look at the git auto-commit action seems like it could work but I'll let @amstr4d take care of that in #35. For what it's worth, if you're using yarn/npm to version the library you may want to consider using the [version lifecycle methods](https://classic.yarnpkg.com/en/docs/cli/version/#toc-version-lifecycle). That route may reduce some of the complexity presented by the GitHub actions approach.

**Review by Fubinator — APPROVED** [review]
This is LGTM now, thanks

**Comment by Fubinator** [comment]
@mrewers I'm gonna look into the `yarn version` approach, thank you!

**Pull request merged**
