### PR TITLE
Added github action for package build

### LINKED ISSUE #35: GitHub Action to builld automatically
With #34 we can build the project locally. What would be useful now is a Github action that builds the library automatically and updates the repo if changes are merged into main.

We discussed splitting this in #31. @amstr4d do you want to take this?

### PR DESCRIPTION
**Pull request by tchapuis**
# Description

This adds a new Github Action for building and publishing the package on npm. The action is triggered when a new release on Github is created. It clones the project, install dependencies and build the project, using what has been done in PR #34. The action needs a npm token to be set in the environment settings of Github. The action cache the yarn dependencies to speed up the build process

Fixes #35 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Fubinator** [comment]
This is looking good so far. Thank you @amstr4d. The easiest way to test this would be setting the secret and trying to create a new release, right?

**Comment by amstr4d** [comment]
Yeah that's it. I never published a package on npm, so I can't help you with that, sorry. Let me know when you tested it !

**Comment by Fubinator** [comment]
Alright, i'm going to test this out soon. Thank you @tchapuis

**Comment by Fubinator** [comment]
It worked @tchapuis! I'm not sure if it was built for npm, but it was published successfully. Thank you!
The action runs on multiple node versions which fails when you try to publish the same version number more than once, but I'm going to fix that.

**Pull request merged**
